name: donde_app
description: A tinder for restaurants

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  country_code_picker: ^1.3.6
  shared_preferences: ^0.5.6+3
  cloud_firestore: ^0.13.4+2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  auto_size_text: ^2.1.0
  geolocator: ^5.3.0
  google_maps_flutter: ^0.5.25+2
  google_maps_webservice: ^0.0.16
  circular_profile_avatar: ^1.0.6
  contacts_service: ^0.3.10
  rflutter_alert: ^1.0.2
  modal_progress_hud: ^0.1.3
  permission_handler: ^5.0.0+hotfix.2
  firebase_admob: ^0.9.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/hearticon.png
    - images/crossicon.png
    - images/food.jpeg
    - images/refreshicon.png
    - images/logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

